In [ ]:
# 22/06 12:00 PM

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os as os

os.listdir('/content/drive/MyDrive/Colab Notebooks/Supervised Learning/Hotel Recommendation System Using Review Analytics/')

['Hotel Recommendation System Using Review Analytics.ipynb']

In [ ]:
import pandas as pd

df = pd.read_csv('')

df.head()

Empty DataFrame
Columns: [{"nbformat":4, nbformat_minor:0, metadata:{"colab":{"provenance":[], authorship_tag:"ABX9TyOdWRTJZ5Y61SLI+RI/DnRZ"}, kernelspec:{"name":"python3", display_name:"Python 3"}, language_info:{"name":"python"}}, cells:[{"cell_type":"code", execution_count:1, metadata:{"id":"KhwPAIvHXAYZ", colab:{"base_uri":"https://localhost:8080/"}, executionInfo:{"status":"ok", timestamp:1782115993728, user_tz:-240, elapsed:25114, user:{"displayName":"Jeeva Anand", userId:"14224796710521349760"}}, outputId:"25c7d495-4312-4cd0-d4fd-3e255d250461"}, outputs:[{"output_type":"stream", name:"stdout", text:["Mounted at /content/drive\n"]}], source:["# 22/06 12:00 PM\n", \n, from google.colab import drive\n, drive.mount('/content/drive')\n]}, {"cell_type":"code", source:["import os as os\n", \n.1, os.listdir('/content/drive/MyDrive/Colab Notebooks/Supervised Learning/')], metadata:{"colab":{"base_uri":"https://localhost:8080/"}, id:"x_TVm2pPY6eU", executionInfo:{"status":"ok".1, timestamp:1782116118812, user_tz:-240.1, elapsed:15, user:{"displayName":"Jeeva Anand".1, userId:"14224796710521349760"}}.1, outputId:"da0e8cca-6a01-48d8-b5c7-8455722f6057"}, execution_count:11, outputs:[{"output_type":"execute_result", data:{"text/plain":["['Loan Prediction ', \n",  'Sentiment Analysis',\n,  'IPL win prediction',\n,  'Time series forcasting',\n,  'WhatsApp Chat Analysis',\n,  'Hotel Recommendation System Using Review Analytics.ipynb']]}, metadata:{}, execution_count:11}]}, {"cell_type":"code".1, source:["import pandas as pd\n", \n.2, df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Supervised Learning/Hotel Recommendation System Using Review Analytics.ipynb')\n, \n.3, df.head()], metadata:{"colab":{"base_uri":"https://localhost:8080/", height:356}, id:"Q8dj9z8nZQKw", executionInfo:{"status":"error", timestamp:1782116099086, user_tz:-240.2, elapsed:99, user:{"displayName":"Jeeva Anand".2, userId:"14224796710521349760"}}.2, outputId:"d23a378f-abcc-4a51-ca01-f0a00beabdc1"}, execution_count:8, outputs:[{"output_type":"error", ename:"IsADirectoryError", evalue:"[Errno 21] Is a directory: '/content/drive/MyDrive/Colab Notebooks/Supervised Learning/Hotel Recommendation System Using Review Analytics.ipynb'", traceback:["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m", \u001b[0;31mIsADirectoryError\u001b[0m                         Traceback (most recent call last), \u001b[0;32m/tmp/ipykernel_1317/2091863161.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_csv\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'/content/drive/MyDrive/Colab Notebooks/Supervised Learning/Hotel Recommendation System Using Review Analytics.ipynb'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhead\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n, \u001b[0;32m/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py\u001b[0m in \u001b[0;36mread_csv\u001b[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)\u001b[0m\n\u001b[1;32m   1024\u001b[0m     \u001b[0mkwds\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkwds_defaults\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1025\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1026\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0m_read\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilepath_or_buffer\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1027\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1028\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n, \u001b[0;32m/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py\u001b[0m in \u001b[0;36m_read\u001b[0;34m(filepath_or_buffer, kwds)\u001b[0m\n\u001b[1;32m    618\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    619\u001b[0m     \u001b[0;31m# Create the parser.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 620\u001b[0;31m     \u001b[0mparser\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mTextFileReader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilepath_or_buffer\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    621\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    622\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mchunksize\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0miterator\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n, \u001b[0;32m/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, f, engine, **kwds)\u001b[0m\n\u001b[1;32m   1618\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1619\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhandles\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mIOHandles\u001b[0m \u001b[0;34m|\u001b[0m \u001b[0;32mNone\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1620\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_engine\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_make_engine\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mengine\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1621\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1622\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m->\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n, \u001b[0;32m/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py\u001b[0m in \u001b[0;36m_make_engine\u001b[0;34m(self, f, engine)\u001b[0m\n\u001b[1;32m   1878\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0;34m\b\"\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mmode\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1879\u001b[0m                     \u001b[0mmode\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;34m\"b\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1880\u001b[0;31m             self.handles = get_handle(\n\u001b[0m\u001b[1;32m   1881\u001b[0m                 \u001b[0mf\u001b[0m\u001b[0;34m, \u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1882\u001b[0m                 \u001b[0mmode\u001b[0m\u001b[0;34m, \u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n", \u001b[0;32m/usr/local/lib/python3.12/dist-packages/pandas/io/common.py\u001b[0m in \u001b[0;36mget_handle\u001b[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)\u001b[0m\n\u001b[1;32m    871\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mioargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mencoding\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0;34m\b\"\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mioargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmode\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    872\u001b[0m             \u001b[0;31m# Encoding\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 873\u001b[0;31m             handle = open(\n\u001b[0m\u001b[1;32m    874\u001b[0m                 \u001b[0mhandle\u001b[0m\u001b[0;34m, \u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    875\u001b[0m                 \u001b[0mioargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmode\u001b[0m\u001b[0;34m, \u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n".1, \u001b[0;31mIsADirectoryError\u001b[0m: [Errno 21] Is a directory: '/content/drive/MyDrive/Colab Notebooks/Supervised Learning/Hotel Recommendation System Using Review Analytics.ipynb']}]}]}]
Index: []

[0 rows x 82 columns]

In [5]:
import urllib.request as req
from bs4 import BeautifulSoup

user_agent = 'Chrome/108.0.0.0'
headers = {'User-Agent': user_agent}

url = 'https://www.booking.com/reviews/gb/hotel/ibis-edinburgh-centre-st-andrew-square.en-gb.html?aid=357028;label=bin859jc-1DEgdyZXZpZXdzKIICOOgHSAlYA2hQiAEBmAEJuAEXyAEM2AED6AEB-AECiAIBqAIDuALorsuNBsACAdICJGJmMjRmNDIwLTMyMTQtNDVjZS05MDNmLTlhY2NjOWM1MTQ0ZdgCBOACAQ;sid=f12de9e50dc512b87c50bcfe5e61d99b;customer_type=total;hp_nav=0;old_page=0;order=featuredreviews;page=4;r_lang=en;rows=75&'

request = req.Request(url, headers=headers)

res = req.urlopen(request)

html = res.read()

bs = BeautifulSoup(html, 'lxml')

print(bs.prettify)

<bound method Tag.prettify of <!DOCTYPE html>
<!--
You know you could be getting paid to poke around in our code?
We're hiring designers and developers to work in Amsterdam:
https://careers.booking.com/
--><!-- wdot-802 --><html class="noJS b_Unparsed b_Unparsed supports_fontface supports_hyphens" lang="en-gb" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# booking_com: http://ogp.me/ns/fb/booking_com#">
<head profile="http://a9.com/-/spec/opensearch/1.1/">
<script nonce="QTNC6lUUGDs3uTz" src="https://cdn.cookielaw.org/consent/3ea94870-d4b1-483a-b1d2-faf1d982bb31/OtAutoBlock.js" type="text/javascript"></script>
<script nonce="QTNC6lUUGDs3uTz" type="text/javascript">
(function () {
document.addEventListener('click', function(e) {
if (e.target && e.target.classList.contains('ot-preference-center-footer')) {
e.preventDefault();
Optanon && Optanon.ToggleInfoDisplay();
}
});
document.addEventListener('cookie_banner_closed', function(e) {
if (window.PCM && window.B && window.B.et) {
window.B.et.goal((window.PCM.Marketing || window.PCM.Analytical) ? 'cookie_consent_accepted_policy_banner' : 'cookie_consent_declined_policy_banner');
}
});
})();
</script>
<script nonce="QTNC6lUUGDs3uTz" type="text/javascript">
window.PCM = {
config: {
isBanner: true,
domainUUID: '3ea94870-d4b1-483a-b1d2-faf1d982bb31',
isPCSIntegration: true,
shareConsentWithin: 'www.booking.com',
isCrossDomainCookieSharingEnabled: false,
nonce: 'QTNC6lUUGDs3uTz',
countryCode: 'tw',
regionCode: 'tpe',
isUserLoggedIn: false,
},
pcm_consent_cookie: ''
};
(()=>{let e,v=e=>{let n,t,o=new FormData,i={error:e.message||"",message:e.message||"",stack:e.stack||"",name:"js_errors",colno:0,lno:0,url:window.location.hostname+window.location.pathname,pid:(null==(t=null==(n=window.B)?void 0:n.env)?void 0:t.pageview_id)||1,be_running:1,be_column:0,be_line:0,be_stack:e.stack||"",be_message:e.message||"",be_file:window.location.hostname+window.location.pathname};Object.keys(i).forEach(e=>{o.append(e,i[e])}),window.fetch("/js_errors",{method:"POST",body:o}).catch(()=>!1)};window.cookieStore&&window.cookieStore.addEventListener("change",e=>{var n;null!=(n=null==e?void 0:e.changed)&&n.length&&null!=e&&e.changed.forEach(e=>{"OptanonAlertBoxClosed"!==e.name||M(e.value)||v(new Error("OptanonAlertBoxClosed bad value detected: "+e.value)),"OptanonConsent"!==e.name||L(e.value)||v(new Error("OptanonConsent bad value detected: "+e.value))})});let h;(n=h=h||{}).ANALYTICAL="C0002",n.MARKETING="C0004";let A;(n=A=A||{}).PREFERENCES_SAVE_SETTINGS="preferences_save_settings",n.BANNER_REJECT_ALL="banner_reject_all",n.BANNER_ACCEPT_ALL="banner_accept_cookies",n.PREFERENCES_REJECT_ALL="preferences_reject_all",n.PREFERENCES_ACCEPT_ALL="preferences_allow_all";let w,N=((n=w=w||{}).BACKFILLING="back_filling",n.GPC_SIGNAL="gpc_signal",n.BACKFILLING_MISMATCH="back_filling_mismatch",n.BACKFILLING_EXPIRED="back_filling_expired",[A.BANNER_ACCEPT_ALL,A.PREFERENCES_ACCEPT_ALL,A.PREFERENCES_SAVE_SETTINGS]),E=[A.BANNER_REJECT_ALL,A.PREFERENCES_REJECT_ALL,A.PREFERENCES_SAVE_SETTINGS],t,B=new Promise(function(e){t=e}),G=window.B&&window.B.env&&window.B.env.b_user_genius_status&&window.B.env.b_user_genius_status.b_genius_level?"genuis_level_"+window.B.env.b_user_genius_status.b_genius_level:"",O={analytical:h.ANALYTICAL+"%3A1",marketing:h.MARKETING+"%3A1"};var n=()=>{var e=P("isDev"),n=window.location.hostname.toLowerCase();return e||n.includes("test.")||n.includes("dqs.")||n.includes("localhost")};let j="%2C",o="bkng_wvpc",i=window.location.hostname,y=P("isPCSIntegration")||!1,a=P("shareConsentWithin")||!1;var r,K=P("cookieDomain")||i,s=null!=(e=P("isCrossDomainCookieSharingEnabled"))&&e;let l=";domain="+(s?"":".")+K;n()&&(l="");let p,d=(p="localhost"===i?"http://localhost:8080/dqs":n()?"https://account.dqs.booking.com":"https://account.booking."+(/booking\.cn/.test(window.location.origin)?"cn":"com"),31536e6),F=15552e6,k="function"==typeof XDomainRequest,U=P("domainUUID")||"",c=P("nonce"),C=P("isBanner")||!1,_=P("isUserLoggedIn"),u=!1;function P(e){return window.PCM&&window.PCM.config&&void 0!==window.PCM.config[e]?window.PCM.config[e]:null}a&&s&&Object.defineProperty(window,"otStubData",{set:function(e){e&&e.domainData&&e.domainData.ScriptType&&"PRODUCTION"===e.domainData.ScriptType&&(e.domainData.ScriptType="TEST"),this._otStubData=e},get:function(){return this._otStubData}});let g=()=>{var e,n=P("countryCode"),t=P("regionCode"),o=null==(o=null==(e=window.OneTrust)?void 0:e.getGeolocationData)?void 0:o.call(e);return{country:n||(null==o?void 0:o.country)||"",region:t||(null==o?void 0:o.state)||""}};function b(e){e=R(e);let n={};return"string"==typeof e&&(e=e.split("&")).length&&e.forEach(function(e){e=e.split("=");2===e.length&&(n[e[0]]=e[1])}),n}function m(n){return Object.keys(n).map(function(e){return e+"="+n[e]}).join("&")}function f(e){var n=document.createElement("iframe");n.onload=t,n.src="https://"+a+"/cookiebanner.html",n.id="OTcrossDomain",n.role="none",n.frameborder="0",n.height="0",n.width="0",n.role="none";return n.setAttribute("style","position: absolute; overflow: hidden; clip: rect(0 0 0 0); width: 1px; height: 1px; margin: -1px; padding: 0; white-space: nowrap; border: 0; clip-path: inset(100%);"),n.setAttribute("aria-hidden","true"),n.setAttribute("tabindex","-1"),n.setAttribute("data-propagate-only-forced-consent",""+e),document.body.appendChild(n),n}function T(e,n,t=!1){let o={type:"onetrust",OptanonConsent:e},i=(M(n)&&(o.OptanonAlertBoxClosed=n),window.document.getElementById("OTcrossDomain"));(i=t&&!i?f(t):i)&&i.contentWindow&&("true"!==(e=i.getAttribute("data-propagate-only-forced-consent"))||"true"===e&&t)&&B.then(function(){var e,n="https://"+a;null!=(e=i.contentWindow)&&e.postMessage(o,n)})}function L(e){if(void 0!==e&&null!=e)try{var n=b(e);return 0<Object.keys(n).length}catch(e){}}function M(e){if(void 0!==e&&null!=e&&isNaN(+e))return e=new Date(e),!isNaN(e.getTime())}function S(e,n,t,o){window.PCM.__mustInjectSDK||void 0===window.Optanon||void 0===e||(e=-1<e.indexOf(t),(void 0!==window.OptanonActiveGroups?-1<window.OptanonActiveGroups.indexOf(n):void 0)!==(window.PCM[o]=e)&&window.Optanon.UpdateConsent("Category",n+":"+(e?"1":"0")))}function D(){var e=b(window.PCM.__getCookie("OptanonConsent"));S(e.groups,h.ANALYTICAL,O.analytical,"Analytical"),S(e.groups,h.MARKETING,O.marketing,"Marketing")}function I(n,t){if(L(n)){let e;var o=(e=M(t)?new Date(t):new Date).getTime()+d,o=new Date(o).toUTCString(),n=R(n);document.cookie="OptanonConsent="+n+l+";path=/;expires="+o+";secure;samesite=none;",M(t)&&(document.cookie="OptanonAlertBoxClosed="+t+l+";path=/;expires="+o+";secure;samesite=none;"),D()}}function x(n,t,o,i){if(y){u=!0;let e=new XMLHttpRequest;e.withCredentials=!0,e.onload=function(){200===e.status?("function"==typeof window.refreshPacs&&window.refreshPacs([{consentType:"ANALYTICAL_COOKIE",value:Boolean(n.analytical)},{consentType:"MARKETING_COOKIE",value:Boolean(n.marketing)}]),o()):(u=!1,i&&i())},e.open("POST",p+"/privacy-consents",!0),e.setRequestHeader("Content-type","application/json;charset=UTF-8"),e.send(JSON.stringify(Object.assign({client_type:"web",client_id:"vO1Kblk7xX9tUn2cpZLS",optanon_action:t,genius_status:G},n)))}}function R(e){return e=e&&-1<e.indexOf("%253")?decodeURI(e):e}function q(e,n){e.backfilled_at=(new Date).getTime(),e.backfilled_seed=1;e=m(e);I(e,n),T(e,n)}let J=()=>"us"!==g().country?F:d;function H(){P("OTAutoBlockScriptLoadedCheck")&&window.setTimeout(()=>{var e,n,t,o;e=document.createElement("script"),n=Object.getOwnPropertyDescriptor(e,"src"),t=Object.getOwnPropertyDescriptor(e,"type"),o=Object.getOwnPropertyDescriptor(e,"class"),e=Object.getOwnPropertyDescriptor(e,"setAttribute"),n&&"function"==typeof n.get&&"function"==typeof n.set&&t&&"function"==typeof t.get&&"function"==typeof t.set&&o&&"function"==typeof o.set&&e&&"function"==typeof e.value||(n=g().country,v(new Error("OtAutoBlock.js is not loaded, country: "+n)))},5e3)}function X(){if(y&&!u){let t=new XMLHttpRequest;t.withCredentials=!0,t.onload=function(){var e,n;200===t.status&&((e=b(window.PCM.__getCookie("OptanonConsent"))).implicitConsentCountry=C?"GDPR":"nonGDPR",e.implicitConsentDate=(new Date).getTime(),e=m(e),n=(new Date).getTime()+d,n=new Date(n).toUTCString(),document.cookie="OptanonConsent="+e+l+";path=/;expires="+n+";secure;samesite=none;",D(),T(e,window.PCM.__getCookie("OptanonAlertBoxClosed")),"function"==typeof window.refreshPacs)&&window.refreshPacs()},t.open("POST",p+"/privacy-consents/implicit",!0),t.setRequestHeader("Content-type","application/json;charset=UTF-8"),t.send(JSON.stringify({client_type:"web",client_id:"vO1Kblk7xX9tUn2cpZLS"}))}}let Y={a:"analytical",m:"marketing"};function W(){var e,n;let t=(e=>{if(e){var n=e.split("&"),t={};for(let e=0;e<n.length;e++){var o=n[e].split(":");if(2!==o.length)return;var i=o[0],o=o[1],i=Y[i];if(!i)return;t[i]="1"===o}return t}})(window.PCM.__getCookie(o));t&&((e=b(window.PCM.__getCookie("OptanonConsent"))).groups=Object.keys(t).filter(function(e){return t[e]}).map(function(e){return O[e]}).join(j),I(e=m(e),n=(new Date).toISOString()),T(e,n),window.PCM.__deleteCookie(o))}function V(e,n){try{if(!k){I(e,n),c=window.PCM.__getCookie("OptanonConsent"),u=window.PCM.pcm_consent_cookie,c&&u&&(l=-1<((c=b(c)).groups||"").indexOf(O.analytical)?1:0,c=-1<(c.groups||"").indexOf(O.marketing)?1:0,d="true"===(u=b(u.replace(/&amp;/g,"&"))).analytical?1:0,u="true"===u.marketing?1:0,k||l==d&&c==u||x({analytical:l,marketing:c},w.BACKFILLING_MISMATCH,()=>{}));var t=window.navigator.globalPrivacyControl,o=g().country;if(y&&t&&"us"===o.toLowerCase()){let a=b(window.PCM.__getCookie("OptanonConsent"));t=[],o=(a.consentCausedByGPCSignalStored||t.push(new Promise(function(e,n){x({analytical:0,marketing:0,is_first_time_gpc_signal:1},w.GPC_SIGNAL,function(){e({consentCausedByGPCSignalStored:(new Date).getTime()})},function(){n({})})})),null===_||_);o&&!a.dnsmiCapturedTimestamp&&t.push(new Promise(function(e,n){let t=new XMLHttpRequest;t.withCredentials=!0,t.onload=function(){200<=t.status&&t.status<=299?e({dnsmiCapturedTimestamp:(new Date).getTime()}):n({})},t.open("POST",p+"/dnsmi",!0),t.setRequestHeader("Content-type","application/json;charset=UTF-8"),t.send()})),Promise.allSettled(t).then(function(n){let t=!1;for(let e=0;e<n.length;e++){var o=n[e];"fulfilled"===o.status&&(Object.assign(a,o.value),t=!0)}var e,i;t&&(e=window.PCM.__getCookie("OptanonAlertBoxClosed"),I(i=m(a),e),T(i,e))})}W(),r=window.PCM.__getCookie("OptanonAlertBoxClosed"),s=J(),M(r)&&(new Date).getTime()-new Date(r).getTime()<=s||(r=b(window.PCM.__getCookie("OptanonConsent")),i=(new Date).getTime(),a=parseInt(r.implicitConsentDate),(!r.implicitConsentDate||s<=i-a||(s=C?"GDPR":"nonGDPR",r.implicitConsentCountry!==s))&&X()),!function(){var e,n,t;y&&(n=window.PCM.__getCookie("OptanonConsent"),e=window.PCM.__getCookie("OptanonAlertBoxClosed"),L(n))&&M(e)&&(n=b(n),t=new Date(e),n.groups)&&(void 0===n.backfilled_at||new Date(parseInt(n.backfilled_at))<t)&&x({analytical:-1<n.groups.indexOf(O.analytical)?1:0,marketing:-1<n.groups.indexOf(O.marketing)?1:0,consented_at:t.toISOString()},w.BACKFILLING_EXPIRED,q.bind(this,n,e))}(),window.PCM.__injectSDK(),H()}}catch(e){v(e)}var i,a,r,s,l,d,c,u}let $=(e,n)=>{"complete"===document.readyState?window.PCM.__dispatchEvent(e,n):window.addEventListener("load",function(){window.PCM.__dispatchEvent(e,n)})};window.OptanonWrapper=function(...e){var n,t=void 0!==window.Optanon&&"function"==typeof window.Optanon.GetDomainData?window.Optanon.GetDomainData().ShowAlertNotice:void 0,o=(D(),document.getElementById("onetrust-policy-text"));if(o&&!o.hasAttribute("tabindex")&&o.setAttribute("tabindex","0"),t)for(let e=window.PCM.__eventCounter;e<window.dataLayer.length;e++)"trackOptanonEvent"!==window.dataLayer[e].event&&"trackOptanonEvent"!==window.dataLayer[e][1]||(n=(window.dataLayer[e].optanonAction||window.dataLayer[e][2].optanonAction).toLowerCase().replace(/\s/g,"_"),-1===N.indexOf(n)&&-1===E.indexOf(n))||(window.PCM.syncConsent(n),window.PCM.__dispatchEvent("cookie_banner_closed")),window.PCM.__eventCounter++;else window.PCM.__dispatchEvent("cookie_consent_available");"function"==typeof window.OptanonWrapperCallback&&window.OptanonWrapperCallback(e)},window.PCM=Object.assign({Marketing:!1,Analytical:!1,__eventCounter:0,__mustInjectSDK:!0,__npmVersion:"2.2.28",__dispatchEvent:function(e,n){n=n||window.PCM;let t;CustomEvent?(t=document.createEvent("CustomEvent")).initCustomEvent(e,!0,!0,n):t=new CustomEvent(e,{detail:n}),document.dispatchEvent(t)},__injectSDK:function(){var e,n;window.PCM.__mustInjectSDK&&(M(null!=(n=window.PCM.__getCookie("OptanonAlertBoxClosed"))?n:"")||window.PCM.__deleteCookie("OptanonAlertBoxClosed"),(n=document.createElement("script")).type="text/javascript",n.setAttribute("async","true"),n.setAttribute("src","https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"),n.setAttribute("charset","UTF-8"),n.setAttribute("data-document-language","true"),n.setAttribute("data-domain-script",U),c&&n.setAttribute("nonce",c),n.addEventListener("load",function(){$("cookie_banner_loaded",{willBannerBeShown:!window.PCM.isUserGaveConsent()})}),n.addEventListener("error",function(){$("cookie_banner_loaded",{willBannerBeShown:!1})}),null!=(e=null==(e=document.getElementsByTagName("head"))?void 0:e.item(0))&&e.appendChild(n),window.PCM.__mustInjectSDK=!1)},__getCookie:function(e){e+="=";var n=document.cookie.split(";");let t,o;for(t=0;t<n.length;t+=1){for(o=n[t];" "==o.charAt(0);)o=o.substring(1,o.length);if(0==o.indexOf(e))return o.substring(e.length,o.length)}return null},__deleteCookie:function(e){document.cookie=e+"=;path=/;domain="+i+";expires=Thu, 01 Jan 1970 00:00:01 GMT",document.cookie=e+"=;path=/;domain=;expires=Thu, 01 Jan 1970 00:00:01 GMT"},isUserGaveConsent:()=>{var e,n=window.PCM.__getCookie("OptanonAlertBoxClosed");return!!n&&(e=J(),(new Date).getTime()-new Date(n).getTime()<=e)},syncConsent:function(e=A.BANNER_REJECT_ALL,n){var t=window.PCM.__getCookie("OptanonAlertBoxClosed");let o=window.PCM.__getCookie("OptanonConsent"),i=b(o),a=-1<(i.groups||"").indexOf(O.analytical)?1:0,r=-1<(i.groups||"").indexOf(O.marketing)?1:0,s=!1;var l=(()=>{var e=document.querySelectorAll('input[type="checkbox"][data-optanongroupid]');if(0===e.length)return null;let t={};return e.forEach(e=>{var n=e.getAttribute("data-optanongroupid");n&&(t[n]=e.checked)}),t})(),d=null==l?void 0:l[h.ANALYTICAL],c=null==l?void 0:l[h.MARKETING];if(P("enableOneTrustCookieValueFix")&&l&&(d!=Boolean(a)||c!=Boolean(r))&&window.OneTrust&&(v(new Error("OptanonConsent cookie value & user interface mismatch")),s=!0),s&&(a=d?1:0,r=c?1:0,o=((e,i,a)=>{let r=!1,n=(e||"").replace(/([?&])groups=([^&]*)/,(e,n,t)=>{r=!0;let o=decodeURIComponent(t);return o=(o=o.replace(/C0002:[01]/,"C0002:"+i)).replace(/C0004:[01]/,"C0004:"+a),/C0002:[01]/.test(o)||(o+=",C0002:"+i),/C0004:[01]/.test(o)||(o+=",C0004:"+a),n+"groups="+encodeURIComponent(o)});return r||(n+="&groups="+encodeURIComponent(`C0001:1,C0002:${i},C0004:`+a)),n})(o,a,r)),i=b(o),s&&!window.optanonAPICalledForRevise&&(document.cookie="OptanonConsent=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; domain="+window.location.host,document.cookie="OptanonConsent=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/",null!=(l=window.OneTrust)&&l.UpdateConsent("Category",`${h.ANALYTICAL}:${a},${h.MARKETING}:`+r),window.optanonAPICalledForRevise=!0),T(o,t,n),!k&&y&&x({analytical:a,marketing:r},e,q.bind(this,i,t)),!(-1===E.indexOf(e)||window.PCM.Analytical&&window.PCM.Marketing)){var u=[...window.PCM.Analytical?[]:[h.ANALYTICAL],...window.PCM.Marketing?[]:[h.MARKETING]],w=[];for(let e=0;e<(null==(p=null==(p=null==(p=window.Optanon)?void 0:p.GetDomainData())?void 0:p.Groups)?void 0:p.length);e++){var p=window.Optanon.GetDomainData().Groups[e];p.CustomGroupId&&-1!==u.indexOf(p.CustomGroupId)&&w.push(p)}var C=[],_=document.cookie.split("; ");for(let e=0;e<_.length;e++)C.push(_[e].split("=")[0]);for(let e=0;e<w.length;e++){var g=w[e].Cookies;for(let e=0;e<g.length;e++){var m=[g[e].Name];if(-1!==m[0].indexOf("xx")){var f=new RegExp("^"+m[0].replaceAll("x","\\w")+"$","g");for(let e=0;e<C.length;e++)C[e].match(f)&&m.push(C[e])}for(let e=0;e<m.length;e++)window.PCM.__deleteCookie(m[e])}}}}},window.PCM),void 0===window.dataLayer&&(window.dataLayer=[]),r=function(){a&&i!==a?(window.addEventListener("message",function(e){e&&e.data&&"OneTrustCookies"===e.data.name&&V(e.data.OptanonConsent,e.data.OptanonAlertBoxClosed)}),f(!1)):V()},"loading"===document.readyState?document.addEventListener("DOMContentLoaded",function(){r()}):r()})();
</script>
<link crossorigin="" href="https://cf.bstatic.com" rel="dns-prefetch"/>
<link crossorigin="" href="https://cf.bstatic.com" rel="dns-prefetch"/>
<meta content="strict-origin-when-cross-origin" name="referrer"/>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<script nonce="QTNC6lUUGDs3uTz"> function b_cors_check(supported) { var value = supported ? 1 : 0; if (!/(^|;)\s*cors_js=/.test(document.cookie)) { var d = new Date(); d.setTime(d.getTime() + 60 * 60 * 24 * 365 * 1000); var cookieDomain = '.booking.com' || '.booking.com'; document.cookie = 'cors_js=' + value +'; domain=' + cookieDomain + '; path=/; expires=' + d.toGMTString(); } if (!value) { location.reload(); } } </script>
<script nonce="QTNC6lUUGDs3uTz">(function(d) { d.addEventListener('error', function(e) { if (e.target && e.target.classList.contains('crossorigin-check-js')) { b_cors_check(false); } }, true); })(document); </script>
<script async="" class="crossorigin-check-js" crossorigin="" nonce="QTNC6lUUGDs3uTz" src="https://cf.bstatic.com/static/js/crossorigin_check_cloudfront_sd/2454015045ef79168d452ff4e7f30bdadff0aa81.js"></script>
<script nonce="QTNC6lUUGDs3uTz">
;(function() {
window.b_early_errors = window.b_early_errors || [];
window.onerror = function() {
window.b_early_errors.push(arguments);
};
}());
 </script>
<link data-main-css="1" href="https://cf.bstatic.com/static/css/main_cloudfront_sd.iq_ltr/b23e5d24024e75bd7f6d8371d26e0a20c73b5afe.css" id="main-css-preload" rel="stylesheet"/>
<script nonce="QTNC6lUUGDs3uTz">
document.querySelector('#main-css-preload').addEventListener('load', function() {
window.mainCssWasLoaded = 1;
})
</script>
<link href="https://cf.bstatic.com/static/css/main_exps_cloudfront_sd.iq_ltr/f3f7bce74850e3086e63c198d858b6528c5be8be.css" rel="stylesheet"/>
<link href="https://cf.bstatic.com/static/css/gprof_icons_cloudfront_sd.iq_ltr/f4fa450a0fd6a6ad8cafc28c74bf19a153e53191.css" rel="stylesheet"/>
<link href="https://cf.bstatic.com/static/css/hotel_base_cloudfront_sd.iq_ltr/7fc0e6fce10ddade63b454e5850163f24274429e.css" media="screen" rel="stylesheet" type="text/css"/>
<link href="https://cf.bstatic.com/static/css/hotel_experiments_cloudfront_sd.iq_ltr/610bf90666e482235684dc218855ef55562f7eb0.css" media="screen" rel="stylesheet" type="text/css"/>
<link href="https://cf.bstatic.com/static/css/reviews_standalone_cloudfront_sd.iq_ltr/26fd74ca96c971b4857f64f7ba706615f5acc284.css" media="screen" rel="stylesheet" type="text/css"/>
<link href="https://cf.bstatic.com/static/css/mlt_cloudfront_sd.iq_ltr.css" rel="stylesheet"/>
<style nonce="QTNC6lUUGDs3uTz"> #basiclayout, .basiclayout { margin: 0; } #special_actions { margin: 3px 15px 3px 0; } .ticker_space { margin-top: 3px !important; } #logo_no_globe_new_logo { top: 14px; } .b_msie_6 #top, .b_msie_6 body.header_reshuffle #top {height:61px !important;} .b_msie_6 #special_actions { margin: 3px 15px 3px 0; overflow:visible; } body.header_reshuffle #top { min-height: 50px !important; height: auto !important; } .nobg { background: #fff url("https://cf.bstatic.com/static/img/nobg_all_blue_iq/b700d9e3067c1186a3364012df4fe1c48ae6da44.png") repeat-x; background-position: 0 -50px; } </style>
<link as="script" crossorigin="" href="https://cf.bstatic.com/static/js/core-deps-inlinedet_cloudfront_sd/f62025e692b596dd53ecd1bd082dfd3197944c50.js" nonce="QTNC6lUUGDs3uTz" rel="preload"/>

In [76]:
base_url = 'https://www.booking.com/reviews/gb/hotel/ibis-edinburgh-centre-st-andrew-square.en-gb.html'



url_l = [
    f"{base_url}?page={page};r_lang=en;rows=25"
    for page in range(1, 25)
]

url_bucket = []

for url in url_l:
  url_bucket.append(url)




for pg in url_bucket:
  try:
    response = req.urlopen(pg)
    html = response.read()
  except Exception:
    continue

  soup = BeautifulSoup(html,'html.parser')

  blocks = soup.find_all("div", {"class": "review_item_review_content"})

  name_blocks = soup.find_all("div", {"class": "review_item_reviewer"})

  for block in name_blocks:
      name = block.find("p", class_="reviewer_name")

      if name:
          names.append(name.get_text(strip=True) if name else None)

  for block in blocks:
     review = block.find("span", itemprop="reviewBody")
     staydate = block.find("p", class_="review_staydate")

     data.append({
        "name": name.get_text(strip=True) if name else None,
        "review": review.get_text(strip=True) if review else None,
        "stay_date": staydate.get_text(strip=True) if staydate else None
     })

In [83]:
# print(len(reviews))
# print(len(names))

data

[]

In [72]:


cards = soup.find_all("li", itemprop="review")

cards

[<li class="review_item clearfix" itemprop="review" itemscope="" itemtype="http://schema.org/Review">
 <div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
 <meta content="Booking.com B.V." itemprop="name"/>
 </div>
 <meta content="" itemprop="datePublished"/>
 <p class="review_item_date">
 Reviewed: 21 June 2026
 </p>
 <div class="review_item_reviewer" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
 <div>
 </div>
 <p class="reviewer_name">
 <span itemprop="name">Pal</span>
 </p>
 <span class="reviewer_country">
 <span class="reviewer_country_flag sflag slang-hu">
 </span>
 <span itemprop="nationality" itemscope="" itemtype="http://schema.org/Country">
 <span itemprop="name">Hungary</span></span>
 </span>
 <div class="user_age_group">
 </div>
 <div class="review_item_user_review_count">
 31 reviews
 </div>
 <div class="review_item_user_helpful_count">
 4 helpful votes
 </div>
 </div><!-- .review_item_reviewer -->
 <div class="review_item_review">
 <div class="review_item_review_container lang_ltr">
 <div class="review_item_review_header">
 <div class="review_item_header_score_container">
 <span class="review-score-widget review-score-widget__exceptional review-score-widget__score-only review-score-widget__no-subtext jq_tooltip high_score_tooltip">
 <span aria-label="Scored 10 " class="review-score-badge">
 10
 </span>
 </span>
 <span itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
 <meta content="10" itemprop="ratingValue"/>
 <meta content="10" itemprop="bestRating"/>
 </span>
 </div>
 <div class="review_item_header_content_container">
 <div class="review_item_header_content">
 “<span itemprop="name">Very nice hotel</span>”
 </div>
 </div>
 </div>
 <ul class="review_item_info_tags">
 <li class="review_info_tag">
 <span class="bullet">•</span> Leisure trip
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Couple
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Queen Room
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Stayed 2 nights
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Submitted via mobile
 </li>
 </ul>
 <div class="review_item_review_content">
 <p class="review_pos"><svg aria-hidden="true" aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14">
 <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
 </svg><span itemprop="reviewBody">The hotel is close to the city center, it is clean, and the staff is very nice. The breakfast was also really good.</span></p>
 <p class="review_staydate">
 Stayed in June 2026
 </p>
 </div>
 </div>
 </div>
 </li>,
 <li class="review_item clearfix" itemprop="review" itemscope="" itemtype="http://schema.org/Review">
 <div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
 <meta content="Booking.com B.V." itemprop="name"/>
 </div>
 <meta content="" itemprop="datePublished"/>
 <p class="review_item_date">
 Reviewed: 21 June 2026
 </p>
 <div class="review_item_reviewer" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
 <div>
 </div>
 <p class="reviewer_name">
 <span itemprop="name">Angela</span>
 </p>
 <span class="reviewer_country">
 <span class="reviewer_country_flag sflag slang-ie">
 </span>
 <span itemprop="nationality" itemscope="" itemtype="http://schema.org/Country">
 <span itemprop="name">Ireland</span></span>
 </span>
 <div class="user_age_group">
 </div>
 <div class="review_item_user_review_count">
 25 reviews
 </div>
 </div><!-- .review_item_reviewer -->
 <div class="review_item_review">
 <div class="review_item_review_container lang_ltr">
 <div class="review_item_review_header">
 <div class="review_item_header_score_container">
 <span class="review-score-widget review-score-widget__exceptional review-score-widget__score-only review-score-widget__no-subtext jq_tooltip high_score_tooltip">
 <span aria-label="Scored 10 " class="review-score-badge">
 10
 </span>
 </span>
 <span itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
 <meta content="10" itemprop="ratingValue"/>
 <meta content="10" itemprop="bestRating"/>
 </span>
 </div>
 <div class="review_item_header_content_container">
 <div class="review_item_header_content">
 “<span itemprop="name">Beautiful en-suite room excellent location</span>”
 </div>
 </div>
 </div>
 <ul class="review_item_info_tags">
 <li class="review_info_tag">
 <span class="bullet">•</span> Business trip
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Group
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Standard Twin Room
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Stayed 1 night
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Submitted via mobile
 </li>
 </ul>
 <div class="review_item_review_content">
 <p class="review_neg"><svg aria-hidden="true" aria-label="Negative point" class="bk-icon -fonticon-removecircle review_item_icon" fill="#BDBDBD" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14"><path d="m16 0c-8.84 0-16 7.16-16 16s7.16 16 16 16 16-7.16 16-16-7.16-16-16-16zm8 17.6h-16v-3.2h16z"></path></svg><span itemprop="reviewBody">nothing</span></p><p class="review_pos"><svg aria-hidden="true" aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14">
 <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
 </svg><span itemprop="reviewBody">location beautiful en-suite room</span></p>
 <p class="review_staydate">
 Stayed in June 2026
 </p>
 </div>
 </div>
 </div>
 </li>,
 <li class="review_item clearfix" itemprop="review" itemscope="" itemtype="http://schema.org/Review">
 <div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
 <meta content="Booking.com B.V." itemprop="name"/>
 </div>
 <meta content="" itemprop="datePublished"/>
 <p class="review_item_date">
 Reviewed: 21 June 2026
 </p>
 <div class="review_item_reviewer" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
 <div>
 </div>
 <p class="reviewer_name">
 <span itemprop="name">David</span>
 </p>
 <span class="reviewer_country">
 <span class="reviewer_country_flag sflag slang-gb">
 </span>
 <span itemprop="nationality" itemscope="" itemtype="http://schema.org/Country">
 <span itemprop="name">United Kingdom</span></span>
 </span>
 <div class="user_age_group">
 </div>
 <div class="review_item_user_review_count">
 25 reviews
 </div>
 </div><!-- .review_item_reviewer -->
 <div class="review_item_review">
 <div class="review_item_review_container lang_ltr">
 <div class="review_item_review_header">
 <div class="review_item_header_score_container">
 <span class="review-score-widget review-score-widget__very_good review-score-widget__score-only review-score-widget__no-subtext jq_tooltip">
 <span aria-label="Scored 8.0 " class="review-score-badge">
 8.0
 </span>
 </span>
 <span itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
 <meta content="8" itemprop="ratingValue"/>
 <meta content="10" itemprop="bestRating"/>
 </span>
 </div>
 <div class="review_item_header_content_container">
 <div class="review_item_header_content">
 “<span itemprop="name">Good hotel in the centre of Edinburgh</span>”
 </div>
 </div>
 </div>
 <ul class="review_item_info_tags">
 <li class="review_info_tag">
 <span class="bullet">•</span> Leisure trip
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Solo traveller
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Queen Room
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Stayed 1 night
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Submitted via mobile
 </li>
 </ul>
 <div class="review_item_review_content">
 <p class="review_neg"><svg aria-hidden="true" aria-label="Negative point" class="bk-icon -fonticon-removecircle review_item_icon" fill="#BDBDBD" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14"><path d="m16 0c-8.84 0-16 7.16-16 16s7.16 16 16 16 16-7.16 16-16-7.16-16-16-16zm8 17.6h-16v-3.2h16z"></path></svg><span itemprop="reviewBody">Thought the cooked breakfast was disappointing</span></p><p class="review_pos"><svg aria-hidden="true" aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14">
 <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
 </svg><span itemprop="reviewBody">Great location. Good room. Nice Bar.</span></p>
 <p class="review_staydate">
 Stayed in June 2026
 </p>
 </div>
 </div>
 </div>
 </li>,
 <li class="review_item clearfix" itemprop="review" itemscope="" itemtype="http://schema.org/Review">
 <div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
 <meta content="Booking.com B.V." itemprop="name"/>
 </div>
 <meta content="" itemprop="datePublished"/>
 <p class="review_item_date">
 Reviewed: 19 June 2026
 </p>
 <div class="review_item_reviewer" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
 <div>
 </div>
 <p class="reviewer_name">
 <span itemprop="name">Lisa</span>
 </p>
 <span class="reviewer_country">
 <span class="reviewer_country_flag sflag slang-gb">
 </span>
 <span itemprop="nationality" itemscope="" itemtype="http://schema.org/Country">
 <span itemprop="name">United Kingdom</span></span>
 </span>
 <div class="user_age_group">
 </div>
 <div class="review_item_user_review_count">
 3 reviews
 </div>
 </div><!-- .review_item_reviewer -->
 <div class="review_item_review">
 <div class="review_item_review_container lang_ltr">
 <div class="review_item_review_header">
 <div class="review_item_header_score_container">
 <span class="review-score-widget review-score-widget__superb review-score-widget__score-only review-score-widget__no-subtext">
 <span aria-label="Scored 9.0 " class="review-score-badge">
 9.0
 </span>
 </span>
 <span itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
 <meta content="9" itemprop="ratingValue"/>
 <meta content="10" itemprop="bestRating"/>
 </span>
 </div>
 <div class="review_item_header_content_container">
 <div class="review_item_header_content review_item_header_scoreword">
 <span itemprop="name">
 Superb
 </span>
 </div>
 </div>
 </div>
 <ul class="review_item_info_tags">
 <li class="review_info_tag">
 <span class="bullet">•</span> Leisure trip
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Solo traveller
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Standard Twin Room
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Stayed 1 night
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Submitted via mobile
 </li>
 </ul>
 <div class="review_item_review_content">
 <p class="review_pos"><svg aria-hidden="true" aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14">
 <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
 </svg><span itemprop="reviewBody">Beautiful hotel  , inexcelent location.</span></p>
 <p class="review_staydate">
 Stayed in May 2026
 </p>
 </div>
 </div>
 </div>
 </li>,
 <li class="review_item clearfix" itemprop="review" itemscope="" itemtype="http://schema.org/Review">
 <div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
 <meta content="Booking.com B.V." itemprop="name"/>
 </div>
 <meta content="" itemprop="datePublished"/>
 <p class="review_item_date">
 Reviewed: 19 June 2026
 </p>
 <div class="review_item_reviewer" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
 <div>
 </div>
 <p class="reviewer_name">
 <span itemprop="name">Clark</span>
 </p>
 <span class="reviewer_country">
 <span class="reviewer_country_flag sflag slang-gb">
 </span>
 <span itemprop="nationality" itemscope="" itemtype="http://schema.org/Country">
 <span itemprop="name">United Kingdom</span></span>
 </span>
 <div class="user_age_group">
 </div>
 <div class="review_item_user_review_count">
 6 reviews
 </div>
 </div><!-- .review_item_reviewer -->
 <div class="review_item_review">
 <div class="review_item_review_container lang_ltr">
 <div class="review_item_review_header">
 <div class="review_item_header_score_container">
 <span class="review-score-widget review-score-widget__exceptional review-score-widget__score-only review-score-widget__no-subtext">
 <span aria-label="Scored 10 " class="review-score-badge">
 10
 </span>
 </span>
 <span itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
 <meta content="10" itemprop="ratingValue"/>
 <meta content="10" itemprop="bestRating"/>
 </span>
 </div>
 <div class="review_item_header_content_container">
 <div class="review_item_header_content high_score_word review_item_header_scoreword">
 <span itemprop="name">
 Exceptional
 </span>
 </div>
 </div>
 </div>
 <ul class="review_item_info_tags">
 <li class="review_info_tag">
 <span class="bullet">•</span> Leisure trip
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Solo traveller
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Standard Twin Room
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Stayed 1 night
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Submitted via mobile
 </li>
 </ul>
 <div class="review_item_review_content">
 <p class="review_neg"><svg aria-hidden="true" aria-label="Negative point" class="bk-icon -fonticon-removecircle review_item_icon" fill="#BDBDBD" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14"><path d="m16 0c-8.84 0-16 7.16-16 16s7.16 16 16 16 16-7.16 16-16-7.16-16-16-16zm8 17.6h-16v-3.2h16z"></path></svg><span itemprop="reviewBody">Nothing</span></p><p class="review_pos"><svg aria-hidden="true" aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14">
 <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
 </svg><span itemprop="reviewBody">The staff were extremely helpful and kind</span></p>
 <p class="review_staydate">
 Stayed in June 2026
 </p>
 </div>
 </div>
 </div>
 </li>,
 <li class="review_item clearfix" itemprop="review" itemscope="" itemtype="http://schema.org/Review">
 <div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
 <meta content="Booking.com B.V." itemprop="name"/>
 </div>
 <meta content="" itemprop="datePublished"/>
 <p class="review_item_date">
 Reviewed: 18 June 2026
 </p>
 <div class="review_item_reviewer" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
 <div>
 </div>
 <p class="reviewer_name">
 <span itemprop="name">Susan</span>
 </p>
 <span class="reviewer_country">
 <span class="reviewer_country_flag sflag slang-gb">
 </span>
 <span itemprop="nationality" itemscope="" itemtype="http://schema.org/Country">
 <span itemprop="name">United Kingdom</span></span>
 </span>
 <div class="user_age_group">
 </div>
 <div class="review_item_user_review_count">
 2 reviews
 </div>
 </div><!-- .review_item_reviewer -->
 <div class="review_item_review">
 <div class="review_item_review_container lang_ltr">
 <div class="review_item_review_header">
 <div class="review_item_header_score_container">
 <span class="review-score-widget review-score-widget__exceptional review-score-widget__score-only review-score-widget__no-subtext jq_tooltip high_score_tooltip">
 <span aria-label="Scored 10 " class="review-score-badge">
 10
 </span>
 </span>
 <span itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
 <meta content="10" itemprop="ratingValue"/>
 <meta content="10" itemprop="bestRating"/>
 </span>
 </div>
 <div class="review_item_header_content_container">
 <div class="review_item_header_content">
 “<span itemprop="name">Absolutely loved it! Great place.</span>”
 </div>
 </div>
 </div>
 <ul class="review_item_info_tags">
 <li class="review_info_tag">
 <span class="bullet">•</span> Leisure trip
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Solo traveller
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> The Works
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Stayed 3 nights
 </li>
 <li class="review_info_tag">
 <span class="bullet">•</span> Submitted via mobile
 </li>
 </ul>
 <div class="review_item_review_content">
 <p class="review_neg"><svg aria-hidden="true" aria-label="Negative point" class="bk-icon -fonticon-removecircle review_item_icon" fill="#BDBDBD" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14"><path d="m16 0c-8.84 0-16 7.16-16 16s7.16 16 16 16 16-7.16 16-16-7.16-16-16-16zm8 17.6h-16v-3.2h16z"></path></svg><span itemprop="reviewBody">The food menu could be much improved upon.
 The TV apps didn’t work</span></p><p class="review_pos"><svg aria-hidden="true" aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" focusable="false" height="14" role="presentation" viewbox="0 0 32 32" width="14">
 <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
 </svg><span itemprop="reviewBody">The premier room was fabulous ! I would stay here again without any hesitation. The hotel staff were so lovely and friendly, and I liked the contemporary look of the rooms.  Great location too. Excellent hotel.</span></p>
 <p class="review_staydate">
 Stayed in June 2026
 </p>
 </div>
 </div>
 </div>
 </li>,
 <li class="review_item clearfix" itemprop="review" itemscope="" itemtype="http://schema.org/Review">

In [84]:
base_url = 'https://www.booking.com/reviews/gb/hotel/ibis-edinburgh-centre-st-andrew-square.en-gb.html'



url_l = [
    f"{base_url}?page={page};r_lang=en;rows=25"
    for page in range(1, 3)
]

url_bucket = []

for url in url_l:
  url_bucket.append(url)


reviews = []
dates = []
names = []
data = []

for pg in url_bucket:
  try:
    response = req.urlopen(pg)
    html = response.read()
  except Exception:
    continue

  soup = BeautifulSoup(html,'html.parser')

  cards = soup.find_all("ul", class_="review_list")




  for block in cards:
     review = block.find("span", itemprop="reviewBody")
     date = block.find("p", class_="review_staydate")
     name_span = block.find("span", itemprop="name")

     print(review.get_text(strip=True))


  #    if review:
  #     reviews.append(review.get_text(strip=True) if review else None)

  #    if date:
  #       dates.append(date.get_text(strip=True) if date else None)

  #    if name:
  #         names.append(name.get_text(strip=True) if name else None)

The hotel is close to the city center, it is clean, and the staff is very nice. The breakfast was also really good.
The hotel is close to the city center, it is clean, and the staff is very nice. The breakfast was also really good.

In [101]:
cards = soup.find_all("li", class_="review_item")

reviews = []
dates = []
names = []
reviews_data = []

for item in cards:
    review = item.find("span", itemprop="reviewBody")
    date = item.find("p", class_="review_staydate")
    name = item.find("span", itemprop="name")

    if review:
      reviews.append(review.get_text(strip=True) if review else None)

    if date:
        dates.append(date.get_text(strip=True) if date else None)

    if name:
          names.append(name.get_text(strip=True) if name else None)

    reviews_data.append({
        "name": name.get_text(strip=True) if name else None,
        "review": review.get_text(strip=True) if review else None,
        "stay_date": date.get_text(strip=True) if date else None
    })

reviews_data

[{'name': 'Pal',
  'review': 'The hotel is close to the city center, it is clean, and the staff is very nice. The breakfast was also really good.',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Angela', 'review': 'nothing', 'stay_date': 'Stayed in June 2026'},
 {'name': 'David',
  'review': 'Thought the cooked breakfast was disappointing',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Lisa',
  'review': 'Beautiful hotel  , inexcelent location.',
  'stay_date': 'Stayed in May 2026'},
 {'name': 'Clark', 'review': 'Nothing', 'stay_date': 'Stayed in June 2026'},
 {'name': 'Susan',
  'review': 'The food menu could be much improved upon. \nThe TV apps didn’t work',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Martin',
  'review': "Couldn't get to grips with the aircon and the position of the shower head in the shower is difficult to work with.",
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Sikora',
  'review': 'Very clean. Excellent service and centrally located to all attractions',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'John',
  'review': 'The only negative was the room was smaller than expected but we would stay here again.',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Julie',
  'review': 'Our room was small with little room for suitcases. The breakfast room was cramped.',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Helen',
  'review': 'Love the decor',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Simona',
  'review': 'It was an amazing stay, very friendly staff. Nice rooms, location is amazing as well.',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Shelagh',
  'review': 'Room was very small and cramped. Dinner options - limited and only so-so. Decor was NOT attractive - random, with loud, conflicting colours. PRICE was VERY HIGH!',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Carolee',
  'review': 'The staff couldn’t have been more helpful.',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Eleanor',
  'review': 'Nothing to not like.  All excellent and 100% staff all lovely and helpful.',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'N',
  'review': '- My only wish is to have the coffee machine available in the lobby 24/7.   (There is a kettle with instant coffee and tea in the rooms but, the variety of breakfast coffee in the lobby was delicious!',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'James', 'review': 'Nothing', 'stay_date': 'Stayed in June 2026'},
 {'name': 'Andrew',
  'review': 'The breakfast is a bit of a jumble \nIt involves a lot of side stepping about folk',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Cynthia',
  'review': 'The first night was interesting, the bathroom was extremely small. I almost hit my head on the wash basin when going to the bathroom, the area was too tight; we left for 2 nights, then returned to the hotel to complete our stay and my bathroom was bigger and much more enjoyable (different room)!',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Lily', 'review': 'Nothing', 'stay_date': 'Stayed in June 2026'},
 {'name': 'Greg', 'review': 'Nothing', 'stay_date': 'Stayed in June 2026'},
 {'name': 'Donna',
  'review': 'I did not have a problem with anything',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Angela',
  'review': 'Faultless- can’t think of any improvements.',
  'stay_date': 'Stayed in June 2026'},
 {'name': 'Leslie',
  'review': 'Great spot, good bar and breakfast area, friendly staff and beautiful room.',
  'stay_date': 'Stayed in May 2026'}]

In [104]:
import pandas as pd

df = pd.DataFrame(reviews_data)

df

,name,review,stay_date
0,Pal,"The hotel is close to the city center, it is c...",Stayed in June 2026
1,Angela,nothing,Stayed in June 2026
2,David,Thought the cooked breakfast was disappointing,Stayed in June 2026
3,Lisa,"Beautiful hotel , inexcelent location.",Stayed in May 2026
4,Clark,Nothing,Stayed in June 2026
5,Susan,The food menu could be much improved upon. \nT...,Stayed in June 2026
6,Martin,Couldn't get to grips with the aircon and the ...,Stayed in June 2026
7,Sikora,Very clean. Excellent service and centrally lo...,Stayed in June 2026
8,John,The only negative was the room was smaller tha...,Stayed in June 2026
9,Julie,Our room was small with little room for suitca...,Stayed in June 2026
10,Helen,Love the decor,Stayed in June 2026
11,Simona,"It was an amazing stay, very friendly staff. N...",Stayed in June 2026
12,Shelagh,Room was very small and cramped. Dinner option...,Stayed in June 2026
13,Carolee,The staff couldn’t have been more helpful.,Stayed in June 2026
14,Eleanor,Nothing to not like. All excellent and 100% s...,Stayed in June 2026
15,N,- My only wish is to have the coffee machine a...,Stayed in June 2026
16,James,Nothing,Stayed in June 2026
17,Andrew,The breakfast is a bit of a jumble \nIt involv...,Stayed in June 2026
18,Cynthia,"The first night was interesting, the bathroom ...",Stayed in June 2026
19,Lily,Nothing,Stayed in June 2026
20,Greg,Nothing,Stayed in June 2026
21,Donna,I did not have a problem with anything,Stayed in June 2026
22,Angela,Faultless- can’t think of any improvements.,Stayed in June 2026
23,Leslie,"Great spot, good bar and breakfast area, frien...",Stayed in May 2026